import os
from enum import Enum

import imagehash
from PIL import Image
from PySide6.QtCore import QSettings

from gui.helpers.get_data import PATH_TOOL_FFSUB


TOOL_CODE_MAIN = "videocreator"
REMEMBER_ME = ("r")  # remember
TOOL_CODE_FFSUB = "ffsub"
NAME_APP_UPDATE = "update.exe"
PAE_LG = "crack_duoc_bao_cao_cho_admin_de_nhan_tien"

SETTING_APP = ("Windows Settings", "Config")
SETTING_CONFIG = ("Windows Settings", "Config")
SETTING_CONFIG_SCREEN = ("sc")
SETTING_APP_DATA = ("d")
USER_DATA = ("u")
PATH_INSTALL_TOOL = ("p")
SETTING_VERSION_APP = ("v")

REG_SUCCESS = ("Bạn đã tao tài khoản thành công! Vui lòng liên hệ Admin để kích hoạt tài khoản")
CHUNK_SPLIT_SUB_CHATGPT_TRANSLATE = 5

LOGOUT_ACCOUNT_FE = "LOGOUT_ACCOUNT_FE"
LOGIN_ACCOUNT = "LOGIN_ACCOUNT"
REG_ACCOUNT = "REG_ACCOUNT"
ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
UPDATE_TOOL_AUTOSUB = "UPDATE_TOOL_AUTOSUB"
UPDATE_TOOL_FFSUB = "UPDATE_TOOL_FFSUB"
DOWNLOAD_FILE_UPDATE = "DOWNLOAD_FILE_UPDATE"
EXTRACT_FILE_UPDATE = "EXTRACT_FILE_UPDATE"
CLOSE_APP = "CLOSE_APP"

LOADING_SPINNER = "LOADING_SPINNER"
NOTIFICATION_TOGGLE_CHANGED = "NOTIFICATION_TOGGLE_CHANGED"
NOTIFICATION_REQUEST_SERVER = "NOTIFICATION_REQUEST_SERVER"
UPDATE_BALANCE_API_TTS = "UPDATE_BALANCE_API_TTS"
TTS_GET_VOICE_FINISHED = "TTS_GET_VOICE_FINISHED"
TEXT_TO_SPEECH_FINISHED = "TEXT_TO_SPEECH_FINISHED"
UPDATE_RANGE_PROGRESS_TABLE_PROCESS = "UPDATE_RANGE_PROGRESS_TABLE_PROCESS"
UPDATE_RANGE_PROGRESS_TABLE_PROCESS_ADD_PLUS = "UPDATE_RANGE_PROGRESS_TABLE_PROCESS_ADD_PLUS"
UPDATE_PECENT_RANGE_TTS_CHUNK_TABLE_PROCESS = "UPDATE_PECENT_RANGE_TTS_CHUNK_TABLE_PROCESS"
RENDER_VIDEO_FFMPEG_TTS_CHUNK_ERROR = "RENDER_VIDEO_FFMPEG_TTS_CHUNK_ERROR"
UPDATE_RANGE_PROGRESS_TTS_CHUNK_TABLE_PROCESS = "UPDATE_RANGE_PROGRESS_TTS_CHUNK_TABLE_PROCESS"
UPDATE_RANGE_PROGRESS_TABLE_EXTRACT_PROCESS = "UPDATE_RANGE_PROGRESS_TABLE_EXTRACT_PROCESS"
UPDATE_VALUE_PROGRESS_GET_FRAME_IMAGE = "UPDATE_VALUE_PROGRESS_GET_FRAME_IMAGE"
UPDATE_VALUE_PROGRESS_TRANSLATE_SUB = "UPDATE_VALUE_PROGRESS_TRANSLATE_SUB"
UPDATE_VALUE_PROGRESS_CHECK_LECH_SUB = "UPDATE_VALUE_PROGRESS_CHECK_LECH_SUB"
UPDATE_VALUE_PROGRESS_TRANSLATE_SUB_TAB_EXTRACT = "UPDATE_VALUE_PROGRESS_TRANSLATE_SUB_TAB_EXTRACT"
UPDATE_VALUE_PROGRESS_OCR_TAB_EDIT = "UPDATE_VALUE_PROGRESS_OCR_TAB_EDIT"
UPDATE_VALUE_PROGRESS_TABLE_PROCESS = "UPDATE_VALUE_PROGRESS_TABLE_PROCESS"
UPDATE_VALUE_PROGRESS_FINISHED_TABLE_PROCESS = "UPDATE_VALUE_PROGRESS_FINISHED_TABLE_PROCESS"
UPDATE_VALUE_PROGRESS_TTS_CHUNK_TABLE_PROCESS = "UPDATE_VALUE_PROGRESS_TTS_CHUNK_TABLE_PROCESS"
RESET_VALUE_PROGRESS_TABLE_PROCESS = "RESET_VALUE_PROGRESS_TABLE_PROCESS"
UPDATE_VALUE_PROGRESS_PLUS_TABLE_PROCESS = "UPDATE_VALUE_PROGRESS_PLUS_TABLE_PROCESS"
UPDATE_VALUE_PROGRESS_TABLE_EXTRACT_PROCESS = "UPDATE_VALUE_PROGRESS_TABLE_EXTRACT_PROCESS"
UPDATE_TEXT_TABLE_ADD_SUB = "UPDATE_TEXT_TABLE_ADD_SUB"

UPDATE_STATUS_TABLE_PROCESS = "UPDATE_STATUS_TABLE_PROCESS"
UPDATE_STATUS_TABLE_RENDER = "UPDATE_STATUS_TABLE_RENDER"
UPDATE_STATUS_TABLE_EXTRACT_PROCESS = "UPDATE_STATUS_TABLE_EXTRACT_PROCESS"
ADD_TO_TABLE_PROCESS = "ADD_TO_TABLE_PROCESS"
ADD_TO_TABLE_EXTRACT_PROCESS = "ADD_TO_TABLE_EXTRACT_PROCESS"

ROW_SELECTION_CHANGED_TABLE_EDIT_SUB = "ROW_SELECTION_CHANGED_TABLE_EDIT_SUB"
ROW_SELECTION_CHANGED_TABLE_EXTRACT = "ROW_SELECTION_CHANGED_TABLE_EXTRACT"
ROW_SELECTION_CHANGED_TABLE_ADD_SUB = "ROW_SELECTION_CHANGED_TABLE_ADD_SUB"
LOAD_SUB_IN_TABLE_FINISHED = "LOAD_SUB_IN_TABLE_FINISHED"

TRIM_AUDIO_SLICE = "TRIM_AUDIO_SLICE"
TRIM_VIDEO_SEG_SUB = "TRIM_VIDEO_SEG_SUB"
GET_TOKEN_SERVER_TTS = "GET_TOKEN_SERVER_TTS"
TEXT_TO_SPEECH_DEMO = "TEXT_TO_SPEECH_DEMO"
TEXT_TO_SPEECH_CHUNK = "TEXT_TO_SPEECH_CHUNK"
TEXT_TO_SPEECH_MULTITHREAD = "TEXT_TO_SPEECH_MULTITHREAD"
TEXT_TO_SPEECH_PUSH_PATH_AUDIO = "TEXT_TO_SPEECH_PUSH_PATH_AUDIO"
RENDER_VIDEOPRE_FINISHED = "RENDER_VIDEOPRE_FINISHED"
TEXT_TO_SPEECH_MULTITHREAD_FINISHED = "RESULT_TEXT_TO_SPEECH_MULTITHREAD"
RESULT_TEXT_TO_SPEECH = "RESULT_TEXT_TO_SPEECH"
RESULT_TEXT_TO_SPEECH_V1 = "RESULT_TEXT_TO_SPEECH_V1"
RESULT_TRANSLATE_SUB = "RESULT_TRANSLATE_SUB"
RESULT_TRANSLATE_SUB_PART = "RESULT_TRANSLATE_SUB_PART"
RESULT_TRANSLATE_SUB_EXTRACT = "RESULT_TRANSLATE_SUB_EXTRACT"
RESULT_TRANSLATE_SUB_EXTRACT_PART = "RESULT_TRANSLATE_SUB_EXTRACT_PART"
RESULT_RUN_DEMO_TIMELINE_EDIT_SUB = "RESULT_RUN_DEMO_TIMELINE_EDIT_SUB"
RESULT_EXTRACT_SUB = "RESULT_EXTRACT_SUB"
RESULT_EXTRACT_SUB_SERVER_AI = "RESULT_EXTRACT_SUB_SERVER_AI"
RESULT_EXTRACT_SUB_LINK_YOUTUBE = "RESULT_EXTRACT_SUB_LINK_YOUTUBE"
EXTRACT_SUB_SPEECH_TO_TEXT = "EXTRACT_SUB_SPEECH_TO_TEXT"
EXTRACT_SUB_YOUTUBE_BY_GOOGLE = "EXTRACT_SUB_YOUTUBE_BY_GOOGLE"

CHECK_LIVE_PROXY_FINISHED = "CHECK_LIVE_PROXY_FINISHED"
CHECK_LIVE_PROXY_ON_TTS_V2 = "CHECK_LIVE_PROXY_ON_TTS"
CHECK_LIVE_PROXY_ON_TTS = "CHECK_LIVE_PROXY_ON_TTS_V1"
CHECK_LIVE_PROXY_ON_TRANSLATE_SUB = "CHECK_LIVE_PROXY_ON_TRANSLATE_SUB"
CHECK_LIVE_PROXY_ON_EXTRACT_SUB = "CHECK_LIVE_PROXY_ON_EXTRACT_SUB"
CHECK_LIVE_PROXY_ON_TRANSLATE_SUB_EXTRACT = "CHECK_LIVE_PROXY_ON_TRANSLATE_SUB_EXTRACT"
CHECK_LIVE_PROXY_ON_NETWORK = "CHECK_LIVE_PROXY_ON_NETWORK"

UPDATE_TY_LE_KHUNG_HINH_VIDEO = "UPDATE_TY_LE_KHUNG_HINH_VIDEO"
SET_AUTO_SAVE_SUB = "SET_AUTO_SAVE_SUB"
SET_STATUS_BUTTON_START = "SET_STATUS_BUTTON_START"
DEST_LANGUAGE_CHANGED = "DEST_LANGUAGE_CHANGED"
TRANSLATE_SUB_FINISHED = "TRANSLATE_SUB_FINISHED"
CHECK_LECH_SUB_FINISHED = "CHECK_LECH_SUB_FINISHED"
TRANSLATE_SUB_EXTRACT_FINISHED = "TRANSLATE_SUB_EXTRACT_FINISHED"
OCR_TEXT_FINISHED = "OCR_TEXT_FINISHED"

FIT_VOICE_MATCH_TO_VIDEO = "FIT_VOICE_MATCH_TO_VIDEO"
ADD_VOICE_TO_VIDEO_CHUNK = "ADD_VOICE_TO_VIDEO_CHUNK"
ADD_VOICE_TO_VIDEO_THREAD = "ADD_VOICE_TO_VIDEO_THREAD"
CONCAT_VOICE = "CONCAT_VOICE"
FIT_VIDEO_MATCH_VOICE = "FIT_VIDEO_MATCH_VOICE"
ADD_TO_PROCESS = "ADD_TO_PROCESS"
RENDER_VIDEO_TTS_CHUNK_IN_THREAD = "RENDER_VIDEO_TTS_CHUNK_IN_THREAD"
RENDER_VIDEO_TTS_CHUNK = "RENDER_VIDEO_TTS_CHUNK"
RENDER_VIDEO_TTS_LIST_SPLIT_COMMAND = "RENDER_VIDEO_TTS_LIST_SPLIT_COMMAND"
RENDER_VIDEO_TTS_GHEP_VOICE_COMMAND = "RENDER_VIDEO_TTS_GHEP_VOICE_COMMAND"
Noi_Video_theo_chunk = "Noi_Video_theo_chunk"
VIDEO_RENDER_NOT_TTS = "VIDEO_RENDER_NOT_TTS"
CHECK_DO_LECH_VIDEO = "CHECK_DO_LECH_VIDEO"
CHECK_DO_LECH_PART_SUB = "CHECK_DO_LECH_PART_SUB"
CHECK_DO_LECH_PART_SUMMARY = "CHECK_DO_LECH_PART_SUMMARY"
CLICK_DOC_THU_VOICE = "CLICK_DOC_THU_VOICE"
RESULT_CHECK_DO_LECH_VIDEO = "RESULT_CHECK_DO_LECH_VIDEO"
RESULT_CHECK_DO_LECH_VIDEO_PART = "RESULT_CHECK_DO_LECH_VIDEO_PART"
RESULT_CHECK_DO_LECH_VIDEO_SUMMARY = "RESULT_CHECK_DO_LECH_VIDEO_SUMMARY"
START_RENDER_VIDEO_V1 = "START_RENDER_VIDEO_V1"
RESET_FOLDER_VOICE = "RESET_FOLDER_VOICE"
START_RENDER_VIDEO_TTS = "START_RENDER_VIDEO"
RENDER_VIDEO_V1_FINISHED = "RENDER_VIDEO_V1_FINISHED"
RENDER_VIDEO_FINISHED = "RENDER_VIDEO_FINISHED"
CONCAT_VIDEO_FINAL = "CONCAT_VIDEO_FINAL"
CONCAT_VIDEO_FILE_LIST = "CONCAT_VIDEO_FILE_LIST"
CONCAT_VIDEO_V1 = "CONCAT_VIDEO_V1"
TOGGLE_SPINNER = "TOGGLE_SPINNER"
THAY_THE_SUB_NEU_SUB_CO_DO_LECH_LON = "THAY_THE_SUB_NEU_SUB_CO_DO_LECH_LON"
THEM_KY_TU_NEU_SUB_CO_HAI_KYTU = "THEM_KY_TU_NEU_SUB_CO_HAI_KYTU"
GOP_SUB_DONG_TREN = "GOP_SUB_DONG_TREN"
GOP_SUB_DONG_DUOI = "GOP_SUB_DONG_DUOI"
XOA_SUB_DONG_SO = "XOA_SUB_DONG_SO"
SPLIT_SUB_TRANSLATE_IN_TABLE = "SPLIT_SUB_TRANSLATE_IN_TABLE"
LOAD_SUB_TRANSLATE_CHATGPT = "LOAD_SUB_TRANSLATE_CHATGPT"
LOAD_SUB_TRANSLATE_TXT = "LOAD_SUB_TRANSLATE_TXT"
LOAD_SUB_TRANSLATE_CHATGPT_PART = "LOAD_SUB_TRANSLATE_CHATGPT_PART"

DETECT_IMAGE_TO_TEXT = "DETECT_IMAGE_TO_TEXT"
DETECT_IMAGE_TO_TEXT_PART = "DETECT_IMAGE_TO_TEXT_PART"

LOAD_SUB_TRANSLATE_CHATGPT_TABLE_EXTRACT = "LOAD_SUB_TRANSLATE_CHATGPT_TABLE_EXTRACT"

LOAD_SUB_TRANSLATE_CHATGPT_TABLE_EXTRACT_PART = "LOAD_SUB_TRANSLATE_CHATGPT_TABLE_EXTRACT_PART"
LOAD_SUB_TRANSLATE_TXT_TABLE_EXTRACT = "LOAD_SUB_TRANSLATE_TXT_TABLE_EXTRACT"
TRANSLATE_SUB_PART_TAB_EXTRACT = "TRANSLATE_SUB_PART_TAB_EXTRACT"
OCR_PART_TAB_EDIT = "OCR_PART_TAB_EDIT"
TRANSLATE_SUB_PART = "TRANSLATE_SUB_PART"
PREVIEW_PRE_RENDER = "PREVIEW_PRE_RENDER"
GET_VOICE_PREVIEW = "GET_VOICE_PREVIEW"
CHECK_DO_LECH_TABLE_CHANGED_PART = "CHECK_DO_LECH_TABLE_CHANGED_PART"
CHECK_DO_LECH_DIALOG_SUMMARY = "CHECK_DO_LECH_DIALOG_SUMMARY"
SPLIT_SUB_IN_TABLE = "SPLIT_SUB_IN_TABLE"
POSITION_SUB_IN_TABLE = "POSITION_SUB_IN_TABLE"
SUMMARY_SUB_IN_TABLE = "SUMMARY_SUB_IN_TABLE"
SPLIT_SUB_IN_TABLE_FINISHED = "SPLIT_SUB_IN_TABLE_FINISHED"
SHOW_DATA_TABLE_TIMELINE = "SHOW_DATA_TABLE_TIMELINE"
SHOW_DATA_TABLE_TIMELINE_EXTRACT = "SHOW_DATA_TABLE_TIMELINE_EXTRACT"

STOP_THREAD_OCR = "STOP_THREAD_OCR"
STOP_THREAD_TRANSLATE = "STOP_THREAD_TRANSLATE"
STOP_THREAD_CHECK_DO_LECH = "STOP_THREAD_CHECK_DO_LECH"
STOP_GET_VOICE = "STOP_GET_VOICE"
RENDER_VIDEO_FFMPEG_NO_TTS = "RENDER_VIDEO_FFMPEG"
RENDER_VIDEO_FFMPEG_TTS_LIST_COMMAND = "RENDER_VIDEO_FFMPEG_TTS_LIST_COMMAND"
RENDER_VIDEO_FFMPEG_TTS_CHUNK = "RENDER_VIDEO_FFMPEG_TTS_CHUNK"
RENDER_VIDEO_PRE_TTS = "RENDER_VIDEO_PRE_TTS"
RESULT_CMD_RENDER_VIDEO_PRE_TTS = "RESULT_CMD_RENDER_VIDEO_PRE_TTS"
RENDER_VIDEO_FFMPEG_NO_TTS_FINISHED = "RENDER_VIDEO_FFMPEG_FINISHED_V2"
RENDER_VIDEO_FFMPEG_FINISHED_V1 = "RENDER_VIDEO_FFMPEG_FINISHED_V1"
UPDATE_FILENAME_OUTPUT_RENDER = "UPDATE_FILENAME_OUTPUT_RENDER"
SMART_CUT_VIDEO = "SMART_CUT_VIDEO"
SMART_CUT_VIDEO_HAS_MUSIC = "SMART_CUT_VIDEO_HAS_MUSIC"
CMD_SMART_CUT_VIDEO = "CMD_SMART_CUT_VIDEO"

EXTRACT_SUB_FINISHED = "EXTRACT_SUB_FINISHED"
EXTRACT_SUB_SEQUENCE = "EXTRACT_SUB_SEQUENCE"

DETECT_LANGUAGE_AISUB = "DETECT_LANGUAGE_AISUB"
RUN_CMD_DETECT_SUB = "RUN_CMD_DETECT_SUB"
RUN_CMD_DETECT_SUB_DEMO = "RUN_CMD_DETECT_SUB_DEMO"
RUN_CMD_AISUB = "RUN_CMD_AISUB"
GET_FRAME_FROM_VIDEO = "GET_FRAME_FROM_VIDEO"
START_SERVER_FFSUB_FINISHED = "START_SERVER_FFSUB_FINISHED"
PROCESS_FFSUB_THREAD = "PROCESS_FFSUB_THREAD"
LOAD_VIDEO_FROM_FILE_SRT = "LOAD_VIDEO_FROM_FILE_SRT"
UPDATE_CONTENT_EDIT_BINDING = "UPDATE_CONTENT_EDIT_BINDING"
STOP_EXTRACT_SUB_TABLE = "STOP_EXTRACT_SUB_TABLE"
LOAD_VIDEO_FROM_DROP_FILE = "LOAD_VIDEO_FROM_DROP_FILE"
LOAD_VIDEO_FROM_FILE_SRT_EXTRACT = "LOAD_VIDEO_FROM_FILE_SRT_EXTRACT"
FILE_SRT_CURRENT = "FILE_SRT_CURRENT"
LOAD_FILE_EXTRACT_FINISHED = "LOAD_FILE_EXTRACT_FINISHED"
CHANGE_LANGUAGE_ORIGIN_FROM_TABLE_EXTRACT = "CHANGE_LANGUAGE_ORIGIN_FROM_TABLE_EXTRACT"
ITEM_TABLE_TIMELINE_EXTRACT_CHANGED = "ITEM_TABLE_TIMELINE_EXTRACT_CHANGED"
ITEM_TABLE_TIMELINE_EDIT_SUB_CHANGED = "ITEM_TABLE_TIMELINE_EDIT_SUB_CHANGED"
ITEM_TABLE_TIMELINE_ADD_SUB_CHANGED = "ITEM_TABLE_TIMELINE_ADD_SUB_CHANGED"
UPDATE_TABLE_TIMELINE_TEXT_SUB_CHANGED = "UPDATE_TABLE_TIMELINE_TEXT_SUB_CHANGED"
PLAY_VIDEO_AGAIN = "PLAY_VIDEO_AGAIN"
ACTION_PRESS_PREVIEW = "ACTION_PRESS_PREVIEW"
ACTION_PRESS_SELECT_ALL = "ACTION_PRESS_SELECT_ALL"
ACTION_PRESS_SELECT_OPTION = "ACTION_PRESS_SELECT_OPTION"
ACTION_PRESS_CHECH_DOLECH= "ACTION_PRESS_CHECH_DOLECH"
ACTION_PRESS_GET_VOICE = "ACTION_PRESS_GET_VOICE"
ACTION_PRESS_DELETE_TAB_ADD_SUB = "ACTION_PRESS_DELETE_TAB_ADD_SUB"

ACTION_PRESS_FIND_REPLACE = "ACTION_PRESS_FIND_REPLACE"
ACTION_PRESS_RUT_GON_NOI_DUNG = "ACTION_PRESS_RUT_GON_NOI_DUNG"
ACTION_PRESS_TRANSLATE_AGAIN = "ACTION_PRESS_TRANSLATE_AGAIN"
ACTION_PRESS_OCR_AGAIN = "ACTION_PRESS_OCR_AGAIN"
ACTION_PRESS_DELETE = "ACTION_PRESS_DELETE"
ACTION_PRESS_GOP_SUB = "ACTION_PRESS_GOP_SUB"
ACTION_PRESS_TACH_SUB = "ACTION_PRESS_TACH_SUB"
# BLUR_AREA = 'BLUR_AREA'
ACTION_PRESS_NEXT_LINE_SUB = "ACTION_PRESS_NEXT_LINE_SUB"
ACTION_PRESS_PREVIOUS_LINE_SUB = "ACTION_PRESS_PREVIOUS_LINE_SUB"


START_SERVER_FFSUB = "START_SERVER_FFSUB"
DETECT_SUB_DEMO = "DETECT_SUB_DEMO"
SELECTION_AREA_SUB_CHANGED = "SELECTION_AREA_SUB_CHANGED"
SELECTION_AREA_BLUR_CHANGED = "SELECTION_AREA_BLUR_CHANGED"
STATUS_BUTTON_SAVE_CONFIG_CHANGED = "STATUS_BUTTON_SAVE_CONFIG_CHANGED"
CENTER_POSITION_SUB_ORIGINAL = "CENTER_POSITION_SUB_ORIGINAL"
CENTER_POSITION_SUB_TRANS = "CENTER_POSITION_SUB_TRANS"
CENTER_POSITION_SUB = "CENTER_POSITION_SUB"
CENTER_POSITION_ADD_SUB = "CENTER_POSITION_ADD_SUB"
POSITION_SUB_ORIGINAL_CHANGED = "POSITION_SUB_ORIGINAL_CHANGED"
POSITION_EDIT_SUB_CHANGED = "POSITION_EDIT_SUB_CHANGED"
POSITION_ADD_SUB_CHANGED = "POSITION_ADD_SUB_CHANGED"
POSITION_SUB_CHANGED = "POSITION_SUB_CHANGED"
LOAD_CONFIG_CHANGED = "LOAD_CONFIG_CHANGED"
LOAD_CONFIG_SRT_FILE_CHANGED = "LOAD_CONFIG_SRT_FILE_CHANGED"
LOAD_CONFIG_TAB_EDIT_SUB_CHANGED = "LOAD_CONFIG_TAB_EDIT_SUB_CHANGED"
LOAD_CONFIG_TAB_ADD_SUB_CHANGED = "LOAD_CONFIG_TAB_ADD_SUB_CHANGED"
LOAD_FONT_FAMILY = "LOAD_FONT_FAMILY"

CUT_VIDEO_SEGMENT = "CUT_VIDEO_SEGMENT"
CHANGE_STYLE_SUB = "CHANGE_STYLE_SUB"
CHANGE_HIEN_THI_SUB = "CHANGE_HIEN_THI_SUB"
CHANGE_STYLE_DIALOG_EDIT_SUB = "CHANGE_STYLE_DIALOG_EDIT_SUB"
CHANGE_STYLE_DIALOG_ADD_SUB = "CHANGE_STYLE_DIALOG_ADD_SUB"
CHANGE_FONT_SIZE_TABLE_EDIT_SUB = "CHANGE_FONT_SIZE_TABLE_EDIT_SUB"
CHANGE_COLOR_TABLE_EDIT_SUB = "CHANGE_COLOR_TABLE_EDIT_SUB"
CHANGE_HIEN_THI_TAB_EDIT_SUB = "CHANGE_HIEN_THI_EDIT_SUB"
CHANGE_HIEN_THI_TAB_ADD_SUB = "CHANGE_HIEN_THI_TAB_ADD_SUB"
REFRESH_CONFIG_FILE_SRT_TAB_EDIT = "REFRESH_CONFIG_FILE_SRT_TAB_EDIT"
REFRESH_CONFIG_DATA_APP = "REFRESH_CONFIG_DATA_APP"
REFRESH_CONFIG_FILE_SRT = "REFRESH_CONFIG_FILE_SRT"
REFRESH_REMOVE_CONFIG_FILE_SRT = "REFRESH_REMOVE_CONFIG_FILE_SRT"
REMOVE_CONFIG_FILE_SRT = "REMOVE_CONFIG_FILE_SRT"
REMOVE_CONTENT_WIDGET = "REMOVE_CONTENT_WIDGET"
ADDNEW_SRT_FILE_EDIT_SUB = "ADDNEW_SRT_FILE_EDIT_SUB"
SC_D_CL = "SCAN_DISK_CLIENT"
CHECKOUT_DEPOSIT = "CHECKOUT_DEPOSIT"
CHECK_TRANG_THAI_NAP_TIEN = "CHECK_TRANG_THAI_NAP_TIEN"
CHECK_SO_DU_TAI_KHOAN = "CHECK_SO_DU_TAI_KHOAN"
MUA_HANG_ONLINE = "MUA_HANG_ONLINE"

RELATIVE_PATH = lambda path: os.path.join(os.path.abspath(os.getcwd()), str(path))
JOIN_PATH = lambda relative, path: os.path.join(relative, str(path))
PATH_BROWSERS = RELATIVE_PATH("browsers")
PATH_BROWSERS_CHROMIUM = JOIN_PATH(PATH_BROWSERS, "chromium-1055/chrome-win/chrome.exe")

PATH_AUDIO = RELATIVE_PATH("audio")
PATH_VIDEO = RELATIVE_PATH("video")
PATH_VOICE = RELATIVE_PATH("voice")
if not os.path.exists(PATH_VOICE):
	os.makedirs(PATH_VOICE)
PATH_DB = RELATIVE_PATH("db")
PATH_TEMP = RELATIVE_PATH("temp")
PATH_FONT = RELATIVE_PATH("font")
PATH_OUTPUT = RELATIVE_PATH("output")
PATH_LOGS = RELATIVE_PATH("logs")


# st = QSettings(*SETTING_APP)
# path_install = st.value(PATH_INSTALL_TOOL)
# print(path_install)
def getValueSettings_ (SETTING_VALUE, TOOL_CODE):
	settings = QSettings(*SETTING_APP)
	st_value = settings.value(SETTING_VALUE)
	# print(st_value)
	if st_value is None:
		return None
	
	elif st_value.get(TOOL_CODE) is None:
		return None
	
	elif st_value.get(TOOL_CODE) == '':
		return None
	else:
		return st_value.get(TOOL_CODE)


APP_PATH = os.path.abspath(os.getcwd())

PATH_TEMP_MEDIA = JOIN_PATH(RELATIVE_PATH("images"), "temp")

FILE_NAME_FFSUB_EXE = "ffsub.exe"
FILE_NAME_PYTRAN_DLL = "_pytransform.dll"

FILE_NAME_MAIN_REPLACE = "cudnn64.dll"
FILE_NAME_FAKE_REPLACE = "libprotoc.dll"

FILE_NAME_PYTRAN_MAIN_REPLACE = "cufft64.dll"
FILE_NAME_PYTRAN_FAKE_REPLACE = "libiomp.dll"

FOLDER_REPLACE_TORCH = JOIN_PATH(PATH_TOOL_FFSUB, "torch/lib")
FOLDER_REPLACE_PADDLE = JOIN_PATH(PATH_TOOL_FFSUB, "paddle/libs")

FILE_PYTRAN_MAIN_REPLACE = JOIN_PATH(FOLDER_REPLACE_TORCH, FILE_NAME_PYTRAN_MAIN_REPLACE)
FILE_PYTRAN_FAKE_REPLACE = JOIN_PATH(FOLDER_REPLACE_PADDLE, FILE_NAME_PYTRAN_FAKE_REPLACE)

FILE_FFSUB_MAIN_REPLACE = JOIN_PATH(FOLDER_REPLACE_TORCH, FILE_NAME_MAIN_REPLACE)
FILE_FFSUB_FAKE_REPLACE = JOIN_PATH(FOLDER_REPLACE_TORCH, FILE_NAME_FAKE_REPLACE)

FILE_FFSUB = JOIN_PATH(PATH_TOOL_FFSUB, FILE_NAME_FFSUB_EXE)
FILE_PYTRAN = JOIN_PATH(PATH_TOOL_FFSUB, FILE_NAME_PYTRAN_DLL)

DELIMITER_POS_SUB = ":"
DELIMITER_CENTER_POS_SUB = "_"
LIST_FILE_MUSIC = [
	".mp3",
	".m4a",
	".wma",
	".wav",
	".flac",
]
LIST_FILE_VIDEO = [
	".mp4",
	".avi",
	".wmv",
	".flv",
	".mkv",
	".mov",
]

MODE_DETECT = {
	"exactly": "Chính xác",
	"fast": "Nhanh"
	
}

# ___________________ TEXT TO SPEECH ________________

# ___________________ END TEXT TO SPEECH ________________

LANGUAGES_FORMAT = ["en", "zh-cn", "ch", "chinese_cht"]

MODEL_WHISPER = {
	# "base.en": "- Nhỏ: Chỉ Tiếng Anh - Ram Tối Thiểu 1G",
	# "small.en": "- Vừa: Chỉ Tiếng Anh - Ram Tối Thiểu 2G",
	# "medium.en": "- Lớn: Chỉ Tiếng Anh - Ram Tối Thiểu 5G",
	"base": "- Mô Hình Nhỏ: Đa Ngôn Ngữ - Ram Tối Thiểu 1G",
	"small": "- Mô Hình Vừa: Đa Ngôn Ngữ - Ram Tối Thiểu 2G",
	"medium": "- Mô Hình Lớn: Đa Ngôn Ngữ - Ram Tối Thiểu 5G",
	"large": "- Mô Hình Cực Lớn: Đa Ngôn Ngữ - Ram Tối Thiểu 10G",
	
}

MODE_WHISPER = {
	"n": "- Chính xác - Tốc độ thường",
	"f": "- Nhanh - Tốc độ nhanh",
}
FORMAT_OUTPUT_VIDEO = {
	
	"16:9": {
		"854|480": "SD",
		"1280|720": "HD",
		"1920|1080": "FullHD",
		"2560|1440": "2K",
		"3840|2160": "4K",
	},
	
	"9:16": {
		"480|854": "SD",
		"720|1280": "HD",
		"1080|1920": "FullHD",
		"1440|2560": "2K",
		"2160|3840": "4K"
	},
	"1:1": {
		"600|600": "SD",
		"800|800": "HD",
		"1080|1080": "FullHD Facebook",
		"1500|1500": "2K",
		"2048|2048": "4K Facebook",
	},
	
}

# ["Original", "SD", "HD", "Full HD"]
PRESET_OUTPUT_VIDEO = ['ultrafast',
					   'superfast',
					   'veryfast',
					   'faster',
					   'fast',
					   'medium',
					   'slow',
					   'slower',
					   'veryslow']

OUPUT_FORMAT_SUB = ["Định dạng .srt", "Định dạng .txt"]


class FormatSubEnum(Enum):
	SRT = 0
	TXT = 1


# RENDER_STYLE =["Merge Progress - Phù hợp video ngắn","Split Progress - Phù hợp video ngắn"]
RENDER_STYLE = [
	"Tách Tiến Trình - Ổn định cho mọi thời lượng video",
	# "Gộp Tiến Trình - Tốc độ nhanh, Render Video dưới 2 phút"
]


class RenderStyleEnum(Enum):
	# Gop = 1
	Tach = 0


LANGUAGE_CODE_SPLIT_NO_SPACE = ['jpn', 'zho', 'och']

TEXT_INFO_CHATGPT = "- Do ChatGPT dịch nó hay thêm nhiều câu giải thích phía sau, nên tool sẽ ko lấy tự động, mà các bạn phải làm thủ công bằng tay cho nó chuẩn."
TEXT_INFO_CHATGPT += "\n\n- Nếu muốn sủ dụng ChatGPT-4 miến phí thì hãy vào trình duyệt Microsoft Edge và truy cập vào bing.com tạo 1 tài khoản sau đó vào phần Chat để sử dụng."
TEXT_INFO_CHATGPT += "\n\n - Một số trang web cho sử dụng ChatGPT-Plus miến phí: "
TEXT_INFO_CHATGPT += "\n    + poe.com"
TEXT_INFO_CHATGPT += "\n\n- Mỗi Web ChatGPT sẽ giới hạn ký tự chat khác nhau, nên bạn kiểm tra tài khoản của bạn giới hạn bao nhiêu sau đó nhập số lượng ký tự vào ô INPUT tool sẽ tự động lấy sub tách ra thành nhiều đoạn."


def get_color_do_lech_sub (tempo):
	if tempo > 2:
		color = '#f82438'
	elif tempo > 1.5:
		color = '#ff8a00'
	elif tempo > 1:
		color = '#ffd200'
	
	else:
		color = '#ffffff'
	return color


LIST_COLOR_NAME_DO_LECH = ['Màu Đỏ', 'Màu Cam', 'Màu Vàng', 'Màu Trắng']


def get_index_name_do_lech_sub (tempo):
	if tempo > 2:
		color = 0
	elif tempo > 1.5:
		color = 1
	elif tempo > 1:
		color = 2
	else:
		color = 3
	return color


if __name__ == "__main__":
	mmmm = ["sdsdsd"]
	hash = imagehash.average_hash(Image.open(r'E:/Project/Python/NTSVideoCreator/test/2\\mm (14).jpg'))
	print(hash.__str__())

