
from gui.widgets.py_dialogs.py_dialog_add_intro_outro import PyDialogAddIntroOutro
from gui.widgets.py_dialogs.py_dialog_add_music_bg import PyDialogAddMusicBackground
from gui.widgets.py_dialogs.py_dialog_add_watermark import PyDialogAddWaterMark
from gui.widgets.py_dialogs.py_dialog_config_sub import PyDialogConfigSubText
from gui.widgets.py_dialogs.py_dialog_graphic_media import PyDialogGraphicMedia
from gui.widgets.py_dialogs.py_dialog_graphic_rectangle import PyDialogGraphicRectangle
from gui.widgets.py_dialogs.py_dialog_graphic_text import PyDialogGraphicText
from gui.widgets.py_dialogs.py_dialog_lach_video import PyDialogLachVideo
from gui.widgets.py_dialogs.py_dialog_proxy import PyDialogProxy
from gui.widgets.py_dialogs.py_dialog_tmproxy import PyDialogTMProxy
